server:
  port: 8080

mongo:
  host: localhost
  port: 27017
  user: ""
  password: ""
  database: master

management:
  endpoint:
    env:
      enabled: true
  endpoints:
    web:
      exposure:
        include: info,env

spring:
  jackson:
    default-property-inclusion: non_null

logging:
  level:
    root: INFO
    org.springframework: INFO
    org.aburavov.yourownskilltree.backend.spring: DEBUG
    org.mongodb: INFO
    com.mongodb: INFO
